In [1]:
import pandas as pd

In [7]:
data = pd.read_csv("C:\\Users\\Mayan\\Downloads\\tic_dec90_00S__88_00S.csv\\tic_dec90_00S__88_00S.csv")
data

C:\Users\Mayan\AppData\Local\Temp\ipykernel_24552\3542855192.py:1: DtypeWarning: Columns (115) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("C:\\Users\\Mayan\\Downloads\\tic_dec90_00S__88_00S.csv\\tic_dec90_00S__88_00S.csv")

,410306832,20190415,Unnamed: 2,Unnamed: 3,Unnamed: 4,00361523-8811313,Unnamed: 6,J003615.78-881130.9,4612820611348441984,Unnamed: 9,...,Unnamed: 115,5.5612808399778597,2.7351358622992499,9.0660659771266996,-88.191930762312595,0.12148702225366299,8.7042455073351094E-2,1.1,0,509917610
0,410306834,20190415,NaN,NaN,NaN,00385647-8811549,NaN,J003856.58-881154.2,4.612826e+18,NaN,...,NaN,2.128026,1.099079,9.736101,-88.198523,0.048516,0.036312,1.0,0.0,509917612
1,410306837,20190415,NaN,NaN,NaN,00375937-8812132,NaN,J003759.24-881212.8,4.612826e+18,NaN,...,NaN,17.571855,8.492076,9.498899,-88.203613,0.396477,0.300398,1.0,0.0,509917615
2,410306833,20190415,NaN,NaN,NaN,00385459-8811504,NaN,NaN,4.612826e+18,NaN,...,NaN,5.686281,2.715254,9.728879,-88.197309,0.123619,0.089265,1.0,0.0,509917611
3,410306838,20190415,NaN,NaN,009-000117,00363295-8812294,NaN,J003633.25-881229.3,4.612820e+18,NaN,...,NaN,1.635788,0.861392,9.137767,-88.208143,0.037678,0.028252,1.0,0.0,509917616
4,410306887,20190415,NaN,NaN,008-000069,00354395-8831595,NaN,J003544.04-883159.6,4.612059e+18,NaN,...,NaN,2.355112,1.164960,8.933808,-88.533250,0.052536,0.038230,1.0,0.0,509601690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196795,1921978523,20190415,NaN,NaN,NaN,NaN,NaN,NaN,6.341387e+18,NaN,...,NaN,3.228101,3.177954,299.865857,-88.776267,0.076036,0.098894,1.0,0.0,1694918208
196796,1921980254,20190415,NaN,NaN,NaN,NaN,NaN,NaN,6.341487e+18,NaN,...,NaN,14.287584,12.119144,296.155411,-88.001319,0.320646,0.373940,1.0,0.0,1687897837
196797,1921980071,20190415,NaN,NaN,NaN,NaN,NaN,NaN,6.341483e+18,NaN,...,NaN,1.197531,1.100765,298.451493,-88.067273,0.026800,0.033791,-1.0,-1.0,1692548523
196798,1921980073,20190415,NaN,NaN,NaN,NaN,NaN,NaN,6.341483e+18,NaN,...,NaN,9.587325,9.049862,298.447907,-88.067568,0.224146,0.304262,0.0,0.0,1692548524
196799,1921977369,20190415,NaN,NaN,NaN,NaN,NaN,NaN,6.341142e+18,NaN,...,NaN,1.383283,1.320941,296.689505,-89.436594,0.031719,0.040262,1.0,0.0,1688981831

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196800 entries, 0 to 196799
Columns: 125 entries, 410306832 to 509917610
dtypes: float64(102), int64(3), object(20)
memory usage: 187.7+ MB

In [9]:
data.describe()

,410306832,20190415,Unnamed: 2,Unnamed: 6,4612820611348441984,Unnamed: 9,Unnamed: 10,9.0651364108785408,-88.1919282561812,6.8119602,...,Unnamed: 112,5.5612808399778597,2.7351358622992499,9.0660659771266996,-88.191930762312595,0.12148702225366299,8.7042455073351094E-2,1.1,0,509917610
count,1.968000e+05,196800.0,32.000000,0.0,1.933880e+05,6.544000e+03,0.0,196800.000000,196800.000000,173745.000000,...,0.0,196317.000000,196317.000000,196317.000000,196317.000000,196317.000000,196317.000000,187278.000000,196257.000000,1.968000e+05
mean,8.659635e+08,20190415.0,52400.750000,NaN,5.486267e+18,3.544628e+07,NaN,181.640594,-88.666672,-0.431259,...,NaN,19.545144,15.230480,181.595245,-88.666402,3.705444,3.928684,0.817149,0.011373,9.587787e+08
std,7.044579e+08,0.0,31042.798359,NaN,6.263030e+17,1.308934e+04,NaN,100.663761,0.470436,9.783904,...,NaN,31.586862,30.468017,100.642492,0.470329,26.897690,28.529021,0.555944,0.399883,4.450021e+08
min,2.795350e+07,20190415.0,1007.000000,NaN,4.611686e+18,3.542380e+07,NaN,0.007422,-89.992854,-307.580990,...,NaN,0.002604,0.003146,0.001773,-89.992878,0.002604,0.003146,-1.000000,-1.000000,5.075164e+08
25%,3.947808e+08,20190415.0,30278.000000,NaN,5.188190e+18,3.543454e+07,NaN,97.541028,-88.998424,-5.255020,...,NaN,3.628155,2.827303,97.527921,-88.998136,0.118342,0.118831,1.000000,0.000000,5.659091e+08
50%,7.240766e+08,20190415.0,49060.000000,NaN,5.764628e+18,3.544562e+07,NaN,183.622885,-88.585140,-0.526783,...,NaN,9.842224,7.247538,183.545388,-88.584819,0.300640,0.301338,1.000000,0.000000,7.917046e+08
75%,1.003084e+09,20190415.0,75983.250000,NaN,5.765746e+18,3.545821e+07,NaN,265.592821,-88.269384,4.357520,...,NaN,23.499445,16.955110,265.457520,-88.269194,0.704200,0.685310,1.000000,0.000000,1.321978e+09
max,1.000264e+10,20190415.0,112355.000000,NaN,6.342270e+18,3.546747e+07,NaN,359.999753,-88.000015,209.890000,...,NaN,1225.403000,1225.403000,359.999924,-87.999968,1225.403000,1225.403000,1.000000,1.000000,1.727982e+09

In [15]:
data.dropna(axis=1, how='all', inplace=True) # Drop columns where all elements are NaN

AttributeError: 'NoneType' object has no attribute 'dropna'